name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Force Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app  
    - name: Pod install
      run: pod install
    - name: Build App
      run: xcodebuild -project "HowWeTalk.xcodeproj" -scheme "HowWeTalk" -destination "generic/platform=iOS" -configuration Debug
